# See https://pre-commit.com for more information
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    - id: autoflake
      name: autoflake
      entry: autoflake
      language: python
      language_version:  python3
      types: [python]
      args: ['-i', '--remove-all-unused-imports',  '--ignore-init-module-imports']
    - id: isort
      name: isort (python)
      entry: isort
      language: python
      language_version:  python3
      types: [python]
    - id: black
      name: black
      entry: black
      language: python
      language_version:  python3
      types: [python]
